### PR TITLE
Improve installation and usage instructions

### PR DESCRIPTION
**Pull request by David-davidlxl**
Installation and usage instructions for Jetson Nano have been reorganized. Installation instructions for PC have been added. There have been small improvements in other parts of the README as well.

This PR corresponds to https://github.com/davidmallasen/LiveChess2FEN/pull/27#issuecomment-1638069263 and completes the discussion in #27.

### CODE REVIEW

**Comment by davidmallasen** [comment]
I want to carefully have a look at this, but I definitely would like to keep some generic linux (Ubuntu) instructions, as this was how I originally (and also now) use it.

**Comment by David-davidlxl** [comment]
> I want to carefully have a look at this, but I definitely would like to keep some generic linux (Ubuntu) instructions, as this was how I originally (and also now) use it.

Yep, nothing was deleted from your original instructions contentwise; I just reorganized them and added additional instructions for PC

**Comment by davidmallasen** [comment]
Hello @David-davidlxl . I've reorganized a bit the installation instructions part. Let me know if you see anything that should be changed and if not we can merge this to have a big update in the README!

**Review by davidmallasen — APPROVED** [review]
I'm going to merge this because I also added some new instructions for the jetson nano that should be in the main branch asap. @David-davidlxl please open any issue/pr if you see anything wrong here. Thanks again for your contribution!

**Pull request merged**
