### PR TITLE
Remove a redundant package from PC requirements

### PR DESCRIPTION
**Pull request by David-davidlxl**
The `pygame` package mentioned in #9 has been removed from the PC requirements. (I figured that adding sound effects for move detections would be outside the scope of this project, but interested users could check out [my project](https://github.com/David-davidlxl/Lobsterpincer-Spectator-For-Win-RPi-Combo/tree/main)!)

The `pip` commands for installing all the required PC packages (with the latest-possible versions) have also been added.

### CODE REVIEW

**Comment by davidmallasen** [comment]
Hello @David-davidlxl ,
Indeed, the sound effects would be out of the scope of this project, so good update in the `requirements_pc.txt`!

However, the list of `pip` commands are not needed since we have the requirements file. The way to install this would be by running `pip install -r requirements_pc.txt` (check [this](https://learnpython.com/blog/python-requirements-file/) out). 
From what I'm seeing now, that part in the README could be clarified as currently there are two flows, the Nvidia Jetson Nano one (with the `Setup` and `Jetson Nano 2GB install` sections and the `requirements.txt` file) and the PC version (with the `Setup` section and the `requirements_pc.txt` file). How would you suggest that we improve this?

**Review by davidmallasen — CHANGES_REQUESTED** [review]
Hello @David-davidlxl ,
Indeed, the sound effects would be out of the scope of this project, so good update in the `requirements_pc.txt`!

However, the list of `pip` commands are not needed since we have the requirements file. The way to install this would be by running `pip install -r requirements_pc.txt` (check [this](https://learnpython.com/blog/python-requirements-file/) out). 
From what I'm seeing now, that part in the README could be clarified as currently there are two flows, the Nvidia Jetson Nano one (with the `Setup` and `Jetson Nano 2GB install` sections and the `requirements.txt` file) and the PC version (with the `Setup` section and the `requirements_pc.txt` file). How would you suggest that we improve this?

**Comment by davidmallasen** [comment]
The above can be done by:

First, create a python virtual environment `venv` and install the required packages:
~~~
cd LiveChess2FEN
python -m venv venv
source venv/bin/activate
pip install --upgrade pip
pip install -r requirements_pc.txt
~~~
You will need to source the python environment with `source venv/bin/activate` when you open a new terminal and want to run LiveChess2FEN from it. When doing so, you will see `(venv)` in your terminal prompt.

**Comment by David-davidlxl** [comment]
> However, the list of `pip` commands are not needed since we have the requirements file. The way to install this would be by running `pip install -r requirements_pc.txt` (check [this](https://learnpython.com/blog/python-requirements-file/) out).

Yes, I was fully aware of how to install the required packages using the requirements file, but I wanted to give users the option of installing the latest-possible versions (which I mentioned in the descriptions of the commit and this pull request). Right now these commands would install the exact same versions, but later, say a couple months from now, they might very well install the newer versions.

> From what I'm seeing now, that part in the README could be clarified as currently there are two flows, the Nvidia Jetson Nano one (with the `Setup` and `Jetson Nano 2GB install` sections and the `requirements.txt` file) and the PC version (with the `Setup` section and the `requirements_pc.txt` file). How would you suggest that we improve this?

I was aware of this as well. I was (and am) planning to make another pull request for incorporating the installation instructions for PC.

**Comment by davidmallasen** [comment]
Ah I misunderstood the goal of this PR then, now it is clear. 

However, I still believe that in this repository (which includes the "supported" versions) we should stick to the specific versions in the requirements files. There is no problem in installing a previous version of a library to keep compatibility between all the libraries we use. 

In any case, if a user wants or needs a more updated version of a specific library they could do it with `pip install --upgrade [library]` (which we could add in some developer documentation as help for someone who wants to add a new feature). But for the average user who looks at the repository or README, I think this would add more confusion than help.

**Comment by David-davidlxl** [comment]
> Ah I misunderstood the goal of this PR then, now it is clear.
> 
> However, I still believe that in this repository (which includes the "supported" versions) we should stick to the specific versions in the requirements files. There is no problem in installing a previous version of a library to keep compatibility between all the libraries we use.
> 
> In any case, if a user wants or needs a more updated version of a specific library they could do it with `pip install --upgrade [library]` (which we could add in some developer documentation as help for someone who wants to add a new feature). But for the average user who looks at the repository or README, I think this would add more confusion than help.

I couldn't find a simpler way to install all the latest versions than with the commands in my "pip_commands_for_pc_requirements.txt" (your `pip install --upgrade [library]` only upgrades one library at a time while a command like `pip freeze | %{$_.split('==')[0]} | %{pip install --upgrade $_}` would cause catastrophic dependency disasters). But I'll remove my "pip_commands_for_pc_requirements.txt" for now and we could come back to this when I work on updating the installation instructions for README.

**Review by davidmallasen — APPROVED** [review]
Perfect. Usually when needing some new features from libraries, you only want to update as few things as possible to avoid other features to stop working. I agree we can come back to this later :)

**Pull request merged**
